#!/bin/bash

# Start JVM
startup() {
  echo "This is the Red Hat UBI8 OpenJDK ${JAVA_VERSION} Runtime container."
}

# =============================================================================
# Fire up
startup $*
